Repository AmateursLeague/sneaky-package, pull requests merged in 2024-11, with the labels that each got.

#194 Yashksaini coder/issue186
  package/clip.py
  package/show.py
  package/write.py
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#200 chore: 🤖 Add package.ico file for chrome tab icon
  docs/assets/package.ico
  mkdocs.yml
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#203 Offline updated file structure
  package/clip.py
  package/display.py
  package/offline/__init__.py
  package/offline/clip.py
  package/offline/show.py
  package/offline/support/__init__.py
  package/offline/support/copy_to_clipboard.py
  package/offline/support/display.py
  package/offline/support/list_snippets.py
  package/offline/write.py
  package/show.py
  package/test.py
  package/write.py
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted

#206 ✅ Website Enhancement
  docs/assets/logo.png
  docs/development.md
  docs/index.md
  docs/working.md
  mkdocs.yml
Labels: good first issue, gssoc-ext, level2, hacktoberfest-accepted

#207 Added test cases for offline functions
  package/offline/clip.py
  package/offline/support/display.py
  package/stash/__init__.py
  package/stash/test.py
  tests/test_clip.py
  tests/test_display.py
  tests/test_show.py
  tests/test_write.py
Labels: gssoc-ext, level2, hacktoberfest-accepted
