Repository AmateursLeague/sneaky-package, pull requests merged in 2024-10, with the labels that each got.

#24 Fix: Change directory name from code_snippets to stash
  package/graph.py
  package/models.py
  package/piechart.py
Labels: good first issue, GSSoC'24 Extd, easy

#32 Update graph.py
  package/graph.py
Labels: gssoc-ext, level1, hacktoberfest-accepted

#36 Added file existence check and minimal error handling for plot() function
  package/piechart.py
Labels: gssoc-ext, level1, hacktoberfest-accepted

#56 added snippet_utils.py
  display.py
Labels: enhancement, gssoc-ext, Level-2, hacktoberfest-accepted

#64 Feature: checker for xcliip()
  package/graph.py
Labels: gssoc-ext, Level-1, hacktoberfest-accepted

#61 feat: Added web scraping functionality for cl1p.net
  README.md
  package/clp.py
Labels: help wanted, gssoc-ext, Level-3, hacktoberfest-accepted, Approved

#71 Feat: Added Issues templates
  .github/BUG_report_issue_template.md
  .github/Feature_request_issue_template.md
  .github/changes_in_code_issue_template.md
Labels: gssoc-ext, Level-1, hacktoberfest-accepted

#79 docs: Guidelines for contributing document & Updated READme file
  Contributing.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#81 Final read me
  GSSoC-Ext.png
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted

#90 DOCS: documentation phase 2 how to use this package
  how_to_use_package.md
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#91 Docs: PyPi Setup & Deploy #68
  PyPi_Setup.md
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#106 Test: Test Cases for graph.py, models.py and piechart.py
  how_to_use_package.md
  package/graph.py
  package/models.py
  package/test.py
  tests/test_graph.py
  tests/test_models.py
  tests/test_piechart.py
Labels: gssoc-ext, level3, hacktoberfest-accepted

#115 Allow Output File Extension to Match Input File Extension
  package/write.py
Labels: question, On Hold

#119 Display: added all the features from 3 files
  package/clip.py
  package/display.py
  package/show.py
  package/write.py
Labels: gssoc-ext, level1, hacktoberfest-accepted

#132 Static Site Update: GitHub Pages
  docs/CHANGELOG.md
  docs/LICENSE.md
  docs/about.md
  docs/contributing.md
  docs/index.md
  docs/installation.md
  docs/usage.md
  mkdocs.yml
Labels: gssoc-ext, level3, hacktoberfest-accepted

#148 Feature: Create file now creates a cl1p with Clipboard content
  package/clip.py
  package/create.py
  package/display.py
Labels: gssoc-ext, level2, hacktoberfest-accepted

#155 Test Cases: Test cases for display.py and scrap.py
  tests/test_display.py
  tests/test_scrap.py
Labels: gssoc-ext, level3, hacktoberfest-accepted

#159 Added ls feature to show.py
  package/show.py
Labels: gssoc-ext, level1, hacktoberfest-accepted, Changes Required

#165 Feature Request: Add copy-to-clipboard & file write features
  docs/contributing.md
  package/scrap.py
  package/scrap/__init__.py
  package/scrap/grab.py
  package/test.py
  tests/test_scrap.py
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted

#166 install.sh script added to install the required dependencies.
  install.sh
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted, Assigned
